      
    - name: Install dependencies
      apt:
        name: 
          - python3-pip
        state: present
        update_cache: yes

    - name: Install Docker Python SDK
      pip:
        name:
          - docker
          - docker-compose

    - name: Run container
      docker_container:
        name: wartest
        image: "registry.gitlab.com/xavki/presentations-jenkins/wartest:latest"
        ports:
          - "8081:8080"
        state: started
