- name: update and upgrade apt packages
  apt:
    update_cache: yes
    upgrade: yes

- name: install pip
  apt:
    name: 
      - python3-pip
      - python3-apt
    state: present

- name: ensure pip is available
  command: python3 -m ensurepip
  when: pip_packages.stdout.find('pip') == -1

- name: pip install docker-py
  pip:
    name:
      - docker
      - docker-compose
    executable: pip3

- name: run container
  docker_container:
    name: wartest
    image: "{{ image }}"
    ports: 
      - "8081:8080"
    state: started
