    - name: Install dependencies
      apt:
        name: 
          - python3-pip
          - docker.io
        state: present
        update_cache: yes

    - name: Install Docker Python SDK
      pip:
        name:
          - docker
          - docker-compose

    - name: Ensure Docker service is running
      service:
        name: docker
        state: started
        enabled: yes

    - name: Run container
      docker_container:
        name: wartest
        image: "{{ image }}"
        ports:
          - "8081:8080"
        state: started
      environment:
        DOCKER_API_VERSION: "1.40"
