- name: Install pip
  apt:
    name: python3-pip
    state: present

- name: Install Docker Python SDK and Docker Compose
  pip:
    name:
      - docker
      - docker-compose

- name: Run container
  docker_container:
    name: wartest
    image: "{{ image }}"
    ports:
      - "8081:8080"
    state: started
