- name: Install pip
  apt:
    name: python3-pip
    state: present

- name: Install Docker Python SDK and Docker Compose
  pip:
    name:
      - docker
      - docker-compose
- name: Ensure Docker service is running
  service:
    name: docker
    state: started
    enabled: yes
- name: Run container
  docker_container:
    name: wartest
    image: "{{ image }}"
    ports:
      - "8080:8088"
    state: started
